---
name: t2bce update

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message'
        required: false
      fork:
        description: 'Link to any fork if needed'
        required: false
      branch:
        description: 'Any specific branch to be cloned'
        required: false
jobs:
  Publish-Mainline:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get the latest driver
        id: publish
        run: |
          source ${{ github.workspace }}/version
          echo "kver=${KVER}" >> $GITHUB_ENV

          FORK="${{ github.event.inputs.fork }}"
          if [ -z "$FORK" ]; then
          FORK='https://github.com/deqrocks/t2bce.git'
          fi
          BRANCH="${{ github.event.inputs.branch }}"
          git clone --depth 1 --single-branch --branch "v${KVER}" https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
          if [ -z "$BRANCH" ]; then
          git clone --depth 1 $FORK ${{ github.workspace }}/t2bce-source
          else
          git clone --depth 1 --branch $BRANCH $FORK ${{ github.workspace }}/t2bce-source
          fi
          ${{ github.workspace }}/t2bce-source/generate-kernel-patches.sh \
            ${{ github.workspace }}/linux-stable ${{ github.workspace }}
 
      - name: Cleanup and update the repo
        run: |
          cd ${{ github.workspace }}
          rm -r linux-stable t2bce-source
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          MSG="${{ github.event.inputs.commit_message }}"
          if [ -z "$MSG" ]; then
          MSG="Update t2bce for kernel v${{ env.kver }}"
          fi
          git commit -m "${MSG}"
 
      - name: Push changes to the repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
 
  Publish-LTS:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v7
        with:
          ref: 6.18
          persist-credentials: false
          fetch-depth: 0

      - name: Get the latest driver
        id: publish
        run: |
          source ${{ github.workspace }}/version
          echo "kver=${KVER}" >> $GITHUB_ENV

          FORK="${{ github.event.inputs.fork }}"
          if [ -z "$FORK" ]; then
          FORK='https://github.com/deqrocks/t2bce.git'
          fi
          BRANCH="${{ github.event.inputs.branch }}"
          git clone --depth 1 --single-branch --branch "v${KVER}" https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
          if [ -z "$BRANCH" ]; then
          git clone --depth 1 $FORK ${{ github.workspace }}/t2bce-source
          else
          git clone --depth 1 --branch $BRANCH $FORK ${{ github.workspace }}/t2bce-source
          fi
          ${{ github.workspace }}/t2bce-source/generate-kernel-patches.sh \
            ${{ github.workspace }}/linux-stable ${{ github.workspace }}
 
      - name: Cleanup and update the repo
        run: |
          cd ${{ github.workspace }}
          rm -r linux-stable t2bce-source
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          MSG="${{ github.event.inputs.commit_message }}"
          if [ -z "$MSG" ]; then
          MSG="Update t2bce for kernel v${{ env.kver }}"
          fi
          git commit -m "${MSG}"
 
      - name: Push changes to the repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 6.18
